# Server Configuration
server:
  port: 8080  # The port number on which the Spring Boot application will run. Default is 8080.

# Spring Framework Configuration
spring:
  application:
    name: spring-boot-3.0  # Name of the application, used in logs and identification.

  # Datasource Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver for database connection.
    password: Raysi@2002  # Password for the database user. Keep this secure!
    url: jdbc:mysql://localhost:3306/spring_3  # JDBC URL for the database connection.
    username: root  # Database username. Replace 'root' if using another user.

  # JPA (Java Persistence API) Configuration
  jpa:
    generate-ddl: true  # Enables JPA to generate database schema based on entity classes.
    hibernate:
      ddl-auto: update  # Automatically updates the database schema without data loss.
      # Other options: 'create', 'create-drop', 'none', 'validate'.
    show-sql: true  # Enables logging of SQL statements generated by Hibernate. Useful for debugging.